import { Button, VerticalBox, ScrollView, TextEdit, ComboBox, TabWidget } from "std-widgets.slint";

export component AppWindow inherits Window {
    preferred-width: 1280px;
    preferred-height: 720px;
    default-font-size: 14px;
    in-out property<string> request: "http://httpbin.org/get";
    in-out property<string> result: "No result";
    in-out property<string> method: "GET";
    in-out property<string> body: "{}";
    callback request-get-result();
    callback request-updated(string);
    callback method-updated(string);
    callback body-updated(string);
    VerticalLayout {
        spacing: 5px;
        padding: 5px;
        HorizontalLayout {
            spacing: 5px;
            height: 4rem;
            ComboBox {
                model: ["GET", "POST", "PUT"];
                current-value: "\{root.method}";
                width: 10%;
                selected() => {
                    root.method_updated(self.current-value);
                }
            }
            TextEdit {
                padding: 5px;
                text: "\{root.request}";
                edited() => {
                    root.request_updated(self.text);
                }
            }
            Button {
                padding: 5px;
                primary: true;
                text: "Run";
                clicked => {
                    root.request-get-result();
                }
            }
        }
        HorizontalLayout {
            if (root.method != "GET"): TabWidget {
                width: 50%;
                Tab {
                    title: "Body";
                    VerticalLayout {
                        spacing: 5px;
                        padding: 5px;
                        ScrollView {
                            enabled: true;
                            TextEdit {
                                text: "\{root.body}";
                                read-only: false;
                                width: parent.width;
                                height: parent.height;
                                edited() => {
                                    root.body_updated(self.text);
                                }
                            }
                        }
                    }
                }
                Tab {
                    title: "Query Params";
                    VerticalLayout {
                        spacing: 5px;
                        padding: 5px;
                        ScrollView {
                            enabled: true;
                            TextEdit {
                                text: "Not yet implemented, will take key value pairs";
                                read-only: false;
                                width: parent.width;
                                height: parent.height;
                            }
                        }
                    }
                }
            }
            ScrollView {
                preferred-width: 100%;
                enabled: true;
                TextEdit {
                    text: "\{root.result}";
                    read-only: true;
                    width: parent.width;
                    height: parent.height;
                }
            }
        }
    }
}